---
# source: https://www.jeffgeerling.com/blog/2020/automatically-building-and-publishing-ansible-galaxy-collections

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tag: ''

  pre_tasks:
    - name: Ensure the ANSIBLE_GALAXY_TOKEN environment variable is set
      ansible.builtin.fail:
        msg: ANSIBLE_GALAXY_TOKEN is not set.
      when: "lookup('env', 'ANSIBLE_GALAXY_TOKEN') == ''"

    - name: Ensure the ~/.ansible directory exists
      ansible.builtin.file:
        path: ~/.ansible
        state: directory

    - name: Write the Galaxy token to ~/.ansible/galaxy_token
      ansible.builtin.copy:
        content: |
          token: {{ lookup('env', 'ANSIBLE_GALAXY_TOKEN') }}
        dest: ~/.ansible/galaxy_token

  tasks:
    - name: Template out the galaxy.yml file
      ansible.builtin.file:
        path: ../requirements.yml
        state: absent

    - name: Template out the galaxy.yml file
      ansible.builtin.template:
        src: templates/galaxy.yml.j2
        dest: ../galaxy.yml

    - name: Build the collection
      ansible.builtin.command: >
        ansible-galaxy collection build
        chdir=../

    - name: Publish the collection
      ansible.builtin.command: >
        ansible-galaxy collection publish osism-manager-{{ tag | regex_replace('^v', '') }}.tar.gz
        chdir=../
