---
namespace: osism
name: manager
version: 999.0.0
readme: README.md
authors:
  - OSISM community <info@osism.tech>
description: OSISM manager playbooks
license_file: LICENSE
tags:
  - osism
  - system
  - cloud
  - infrastructure
dependencies: {}
repository: https://github.com/osism/ansible-playbooks-manager.git
documentation: https://osism.github.io/docs/intro/
homepage: https://www.osism.tech
issues: https://github.com/osism/ansible-playbooks-manager/issues
