---
- name: Pull manager images
  hosts: manager

  vars:
    docker_registry: index.docker.io
    images:
      - "{{ ara_server_image }}"
      - "{{ ara_server_mariadb_image }}"
      - "{{ ceph_ansible_image }}"
      - "{{ inventory_reconciler_image }}"
      - "{{ kolla_ansible_image }}"
      - "{{ manager_redis_image }}"
      - "{{ netbox_image }}"
      - "{{ osism_ansible_image }}"
      - "{{ osism_image }}"
      - "{{ osism_netbox_image }}"
      - "{{ postgres_image }}"
      - "{{ traefik_image }}"

  tasks:
    - name: Pull images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      async: 120
      poll: 0
      loop: "{{ images }}"
      register: async_results

    - name: Check sync status
      ansible.builtin.async_status:
        jid: "{{ async_result_item.ansible_job_id }}"
      loop: "{{ async_results.results }}"
      loop_control:
        loop_var: "async_result_item"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 30
      ignore_errors: true
